version: "3.3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - "./packages/frontend/:/app/"
    networks:
      - bp-network

  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    volumes:
      - ./packages/backend:/svr/app
      - "./scripts/wait.sh:/wait.sh"
      - /svr/app/node_modules
    networks:
      - bp-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - bp-pg-db
    links:
      - bp-pg-db

  front-manager:
    container_name: front-manager
    build:
      context: ./packages/front-manager
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${FRONTEND_MANAGER_PORT}:3001"
    volumes:
      - "./packages/front-manager/:/app/"
    networks:
      - bp-network

  mobile:
    container_name: mobile
    build:
      context: ./packages/mobile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    tty: true
    ports:
      - "${REACT_NATIVE_PORT_DEFAULT}:${REACT_NATIVE_PORT_DEFAULT}"
      - "${REACT_NATIVE_PORT_DEBUG_1}:${REACT_NATIVE_PORT_DEBUG_1}"
      - "${REACT_NATIVE_PORT_DEBUG_2}:${REACT_NATIVE_PORT_DEBUG_2}"
    volumes:
      - ./packages/mobile:/opt/mobile/app:delegated
      - ./packages/mobile/package.json:/opt/mobile/package.json
      - ./packages/mobile/yarn.lock:/opt/mobile/yarn.lock
      - notused:/opt/mobile/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused:

networks:
  bp-network:
    driver: bridge
