version: "3.3"

services:
  ui:
    image: yassansplus/frontendbonapp
    container_name: front_end_prod
    ports:
      - '3000:3000'
    networks:
      - bp-network
  backend-prod:
    image: yassansplus/backendbonapp:0.3.1
    container_name: back_end_prod
    env_file: .env
    networks:
      - bp-network
    ports:
      - '4000:4000'
    depends_on:
      - bp-pg-db
    links:
      - bp-pg-db
  bp-pg-db:
    image: postgres:12-alpine
    restart: always
    container_name: bp-pg-db
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'bp-pg-db'
    ports:
      - "5432:5432"
    networks:
      - bp-network

networks:
  bp-network:
    driver: bridge
