name: build backend

on:
  push:
    branches: [ pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
          envkey_JWT_ACCESS_TOKEN_EXPIRATION_TIME_WEB: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME_WEB }}
          envkey_JWT_ACCESS_TOKEN_EXPIRATION_TIME_MOBILE: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME_MOBILE }}
          envkey_URL_API_BACKEND: ${{ secrets.URL_API_BACKEND }}
          envkey_URL_FRONTEND: ${{ secrets.URL_FRONTEND }}
          envkey_URL_FRONTMANAGER: ${{ secrets.URL_FRONTMANAGER }}
          envkey_EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
          envkey_MAIL_HOST: ${{ secrets.MAIL_HOST }}
          envkey_MAIL_USER: ${{ secrets.MAIL_USER }}
          envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          envkey_MAIL_FROM: ${{ secrets.MAIL_FROM }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          envkey_GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_STRIPE_CURRENCY: ${{ secrets.STRIPE_CURRENCY }}
          directory: ./packages/backend/
          file_name: .env
          fail_on_empty: true

      - name: Build & Push Image of backend
        run: |
          cd packages/backend/
          echo "${{ secrets.DOCKERPW }}" | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
          docker image build -f Dockerfile.local --tag yassansplus/backendbonapp:${{ steps.date.outputs.date }}.${{ github.actor }} --tag yassansplus/backendbonapp:develop .
          docker push yassansplus/backendbonapp:${{ steps.date.outputs.date }}.${{ github.actor }}
          docker push yassansplus/backendbonapp:develop