name: build frontend

on:
  push:
    branches: [ pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1

      - name: Make envfile
        run: |
          cd packages/frontend/
          touch .env.local

      - name: Build & Push Image of frontend
        run: |
          cd packages/frontend/
          ls