name: build backend

on:
  push:
    branches: [ pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1

      - name: Build & Push Image of backend
        run: |
          cd packages/backend/
          echo "${{ secrets.DOCKERPW }}" | docker login -u "yassansplus" --password-stdin
          docker image build -f Dockerfile.local --tag yassansplus/backendbonapp:${{ steps.date.outputs.date }}.${{ github.actor }} --tag yassansplus/backendbonapp:develop .
          docker push yassansplus/backendbonapp:${{ steps.date.outputs.date }}.${{ github.actor }}
          docker push yassansplus/backendbonapp:develop