name: build frontend

on:
  push:
    branches: [ pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_URL_BACKEND: ${{ secrets.REACT_APP_URL_BACKEND }}
          envkey_REACT_APP_SOCKET_BACKEND: ${{ secrets.REACT_APP_SOCKET_BACKEND }}
          envkey_REACT_APP_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_AUTH_CLIENT_ID }}
          directory: ./packages/frontend/
          file_name: .env
          fail_on_empty: false

      - name: Build & Push Image of frontend
        run: |
          cd packages/frontend/
          cat .env