name: build front-manager

on:
  push:
    branches: [ pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1

      - name: Build & Push Image for front-manager
        run: |
          cd packages/front-manager/
          echo "${{ secrets.DOCKERPW }}" | docker login -u "yassansplus" --password-stdin
          docker image build -f Dockerfile.local --tag yassansplus/front-managerbonapp:${{ steps.date.outputs.date }}.${{ github.actor }} --tag yassansplus/front-managerbonapp:develop .
          docker push yassansplus/front-managerbonapp:${{ steps.date.outputs.date }}.${{ github.actor }}
          docker push yassansplus/front-managerbonapp:develop