name: ESLint

on:
  push:
    branches: [ pipeline ]
  schedule:
    - cron: '21 6 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run eslint ./packages/front-manager/src/** --ext .js,.jsx,.ts,.tsx