name: Deploy to production
on:
  push:
    branches: [ fix-env ]
  workflow_dispatch:

jobs:

  front-manager:
    name: Build front-manager
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1
      - name: Make envfile for front-manager
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_URL_BACKEND: ${{ secrets.REACT_APP_URL_BACKEND }}
          envkey_REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          directory: packages/front-manager
          file_name: .env
          fail_on_empty: true
      - name: Build & Push Image for front-manager
        run: |
          cd packages/front-manager/
          cat .env