name: Deploy to production
on:
  push:
    branches: [ pipeline ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    # needs: [ frontend, front-manager, backend ]
    steps:
      - name: Log to the server and pull the images from docker hub & run the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd BonApp
            sudo docker-compose down
            sudo docker system prune -a -f
            sudo docker-compose up -d
            sleep 10
            echo "Initializing database 🖥️"
            sudo docker exec back_end_prod yarn schema:sync
            echo "Injecting seeds 💾"
            sudo docker exec back_end_prod yarn seed:run