name: Reusable Workflows
on:
  push:
    branches: [ pipeline ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/reusable-workflows.yml
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."