name: Reusable Workflows
on:
  push:
    branches: [ pipeline ]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/eslint.yml

  test:
    needs: [ reusable_workflow_job ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."