name: Unit tests NestJS
on: [ push, pull_request ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name : Run unit tests
        run: |
          ls ${{ github.workspace }}
        continue-on-error: false