name: Unit tests NestJS
on: [ push ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ${{ github.workspace }}/packages/backend/src/
          yarn run test
      continue-on-error: true