name: Unit tests NestJS
on: [ push, pull_request ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - name: Install ESLint
          run: |
            yarn install
            yarn --version
        - name : Run unit tests
          run: yarn run test ./packages/backend/src/
          continue-on-error: false