name: Unit tests NestJS
on: [ push, pull_request ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        - name : Run unit tests
          run: |
            ls -a
          continue-on-error: true