name: Unit tests NestJS
on: [ pull_request ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        - run: |
          cd ./packages/backend/src/
          yarn run test
          continue-on-error: true