name: Unit tests NestJS
on: [ push, pull_request ]
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - name : Run unit tests
          run: |
            ls ${{ github.workspace }}/packages/
          continue-on-error: false